### ISSUE TITLE
hot reload

### ISSUE THREAD

**Issue by jjangga0214** [rodrigobastosv/round_check_box#4]
Hi, thanks for this useful widget!

I don't know why, but found hot reload does not work properly.

For example, when I change `uncheckedColor` works well, but when `size` is changed, hot reload does not work.

**Comment by rodrigobastosv** [comment]
Hi @jjangga0214, thanks for using this package.

What do you mean with "hot reload does not work"?

Maybe if you send a gif it will be more clear what the error is.

Thanks!
