### ISSUE TITLE
feat(options): border width

### ISSUE THREAD

**Issue by jjangga0214** [rodrigobastosv/round_check_box#5]
Hi!

IMHO, it'd be good if border width can be configured.

How do you think?

Thanks :)

**Comment by rodrigobastosv** [comment]
Hi @jjangga0214, first of all thanks for using this package.

Your suggestion makes perfect sense. I'll make this change soon.

Thanks very much!

**Comment by rodrigobastosv** [comment]
Hi @jjangga0214 , i just released a new version with your suggestion. I even added on the  example a case of a checkbox that configures its own border.

You can check the changes on the 2.0.2 version.

Thanks again for using this package.

I'll close this issue for now but feel free to reopen if needed
