### ISSUE TITLE
(Idea) "Check" Icon Size

### ISSUE THREAD

**Issue by dwilimsius** [rodrigobastosv/round_check_box#8]
Hi @rodrigobastosv , first of all, thanks for the widget, it is really useful for my application looks.

About checkbox size, I know that you've already added an attribute named "size" on it, but when I set the size smaller than 20, the checkbox icon seems like didn't change, if you don't mind, can you set the icon following the size? because I think, in my project, it may be good if the checkbox can be smaller than the text.

Again, many thanks to you for making this widget.

**Comment by dwilimsius** [comment]
oh, I found an attribute called "checkedWidget", I just realized that we can handle that thing with this widget. OK, many thanks @rodrigobastosv

**Comment by rodrigobastosv** [comment]
Thanks for using this package @dwilimsius .
